; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nanoatmega328new

[env]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
build_src_flags =
    -Wall
    -Wextra
lib_deps = 
    adafruit/Adafruit GFX Library@1.11.9
    adafruit/Adafruit BusIO@1.16.1
    https://github.com/wonho-maker/Adafruit_SH1106/archive/f4e427f964f0c41740fe79d2f8944f1ce4de3f1b.zip
    https://github.com/claws/BH1750/archive/refs/tags/1.1.4.zip

[env:nanoatmega328new]
build_flags =
    -Wl,--relax
    -mcall-prologues

[env:nanoatmega328new_debug]
extends = env:nanoatmega328new
build_type = debug
monitor_speed = 57600
build_flags =
    -DLIGHTMETER_DEBUG=1
    -DLIGHTMETER_DEBUG_BAUD=57600
